services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: netflix_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=mypassword pg_isready -U postgres -d netflix_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    container_name: preprocessing_app
    build: .
    depends_on:
      db:
        condition: service_healthy
   
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-netflix_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_HOST: ${POSTGRES_HOST:-db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      INPUT_PATH: /app/data/netflix_titles.csv
      OUTPUT_PATH: /app/cleaned_netflix.csv

    volumes:
      - ./data:/app/data
      - /mnt/c/Users/D-P/desktop/project/netflix-cron.txt:/etc/cron.d/netflix-cron
      - ./scripts:/app/scripts
    command: ["/app/run_pipeline.sh"]


volumes:
  db_data:
